### ISSUE TITLE
Requirements Overview

### ISSUE THREAD

**Issue by SamyAteia** [pragmalingu/search-analysis#1]
### Goals
1. Use-Case: Analyze Single Approach
    **1.1 Approach level** 
         1.1.1 Get Metrics: Precision, Recall, F1-Score (default), F-score. Maybe additional metrics later.
         1.2.2 Find queries that perform especially bad/good. Get querie_ids sorted by recall or precision
    **1.2 Query Level**
        1.2.1 Analyze false positives, false negatives. Look at false positives with highest score, look at false negatives with lowest scores. 
    **1.3 Result Level**
        1.3.1 Get score, show query, show field value. (optional if available: show highlighting, show score calculation (explain)
2. Use-Case Compare Approaches
    **2.1 Approach Level**
         2.1.1 Additional Function get metrics side by side
         2.1.2 Visualization of metrics side by side for approaches(bar chart)
         2.1.3 Find queries where recall or precision scores have biggest difference between two approaches
     **2.2 Query Level**
          2.2.1 Analyze false positives, false negatives, calculate disjoint set, sorted by position. For false positives sort by position highest (1) position first. False negatives sort by position lowest position first.
     **2.3 Result Level**
         2.3.1 get scores in all approaches side by side, (if possible) get highlights and explains in all approaches side by side

         
 

### TODOs:

- [x] (Prio1) Write Function that accepts weighted queries dictionaries (f-score, recall, precision) of two approaches and calculates score difference for each query and sorts by absolute score difference value. (2.1.3)
- [x] Implement function that returns disjoint sets per query (2.2.1)
- [x] Add visualization functions from notebooks.
- [x] (Prio2)  Check and compare rank_eval results to search analysis tool results. Find variations and try to explain them.
- [ ] (Bonus) 2.3.1 if its helpfull for analysis
- [x] Count_Results -> add percent of relevant to count
- [x] Count_Results -> Sorted by count
- [x] Research how to calculate Precision and Recall on set of Queries (Mean, Avg ...)
- [x] Function that returns Precision per query and per approach (avg or mean)
- [x] Function that returns Recall per query and per approach (avg or mean)
- [x] Function that returns query_ids sorted by recall (analogues to count_result)
- [x] Function that returns query_ids sorted by precision  (analogues to count_result)
- [x] Function that returns F-Score (F1 default parameter)

### Issues:

- [x] Check why result lists (false positives, ...) for queries are empty
